"""
Voxel Block Type Mappings

AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
Generated on: 2025-06-08T16:10:39.580992
Source: JSON block definitions + ID registry

This file is automatically generated by scripts/generators/python_generator.py
To update this file, modify the JSON data files and run the generator.
"""

from enum import IntEnum
from typing import Dict, List, Optional, Set

class VoxelType(IntEnum):
    """Enumeration of all voxel block types with their IDs"""
    # TERRAIN BLOCKS
    AIR = 0
    STONE = 1
    DIRT = 2
    GRASS = 3
    SAND = 4
    GRAVEL = 5
    CLAY = 6
    BEDROCK = 7
    TOPSOIL = 8
    SUBSOIL = 9
    GRANITE = 10
    LIMESTONE = 11
    MARBLE = 12
    SANDSTONE = 13
    SLATE = 14
    BASALT = 15
    QUARTZITE = 16
    OBSIDIAN = 17
    PUMICE = 18
    SHALE = 19
    COAL_ORE = 20
    IRON_ORE = 21
    COPPER_ORE = 22
    TIN_ORE = 23
    SILVER_ORE = 24
    GOLD_ORE = 25
    RUBY = 26
    SAPPHIRE = 27
    EMERALD = 28
    DIAMOND = 29
    OAK_WOOD = 30
    PINE_WOOD = 31
    BIRCH_WOOD = 32
    MAHOGANY_WOOD = 33
    OAK_LEAVES = 34
    PINE_LEAVES = 35
    BIRCH_LEAVES = 36
    PALM_LEAVES = 37
    BROWN_MUSHROOM = 38
    RED_MUSHROOM = 39
    SNOW = 40
    ICE = 41
    PACKED_ICE = 42
    CACTUS = 43
    JUNGLE_VINE = 44
    PINK_CORAL = 45
    BLUE_CORAL = 46
    SEAWEED = 47
    TUNDRA_MOSS = 48
    DESERT_ROCK = 49
    TEST_AUTO_ID = 256

    # FLUIDS BLOCKS
    WATER = 50
    LAVA = 51
    OIL = 52
    ACID = 53
    HONEY = 54
    STEAM = 55
    TOXIC_GAS = 56
    NATURAL_GAS = 57
    MAGICAL_MIST = 58
    SMOKE = 59

    # PROCESSED BLOCKS
    STONE_BRICK = 60
    GRANITE_BRICK = 61
    MARBLE_TILE = 62
    SANDSTONE_BRICK = 63
    SLATE_TILE = 64
    COBBLESTONE = 65
    SMOOTH_STONE = 66
    POLISHED_STONE = 67
    CHISELED_STONE = 68
    FLAGSTONE = 69
    OAK_PLANKS = 70
    PINE_PLANKS = 71
    BIRCH_PLANKS = 72
    MAHOGANY_PLANKS = 73
    OAK_BEAM = 74
    PINE_BEAM = 75
    HARDWOOD_BEAM = 76
    BAMBOO_PLANKS = 77
    CORK = 78
    CHARCOAL_BLOCK = 79
    IRON_BLOCK = 80
    COPPER_BLOCK = 81
    BRONZE_BLOCK = 82
    STEEL_BLOCK = 83
    SILVER_BLOCK = 84
    GOLD_BLOCK = 85
    BRASS_BLOCK = 86
    PEWTER_BLOCK = 87
    MITHRIL_BLOCK = 88
    ADAMANTINE_BLOCK = 89
    CLAY_BRICK = 90
    TERRACOTTA = 91
    WHITE_GLAZED_CERAMIC = 92
    RED_GLAZED_CERAMIC = 93
    BLUE_GLAZED_CERAMIC = 94
    GREEN_GLAZED_CERAMIC = 95
    PORCELAIN = 96
    STONEWARE = 97
    EARTHENWARE = 98
    CERAMIC_TILE = 99

    # FUNCTIONAL BLOCKS
    BLOCK_100 = 100
    BLOCK_101 = 101
    BLOCK_102 = 102
    BLOCK_103 = 103
    BLOCK_104 = 104
    BLOCK_105 = 105
    BLOCK_106 = 106
    BLOCK_107 = 107
    BLOCK_108 = 108
    BLOCK_109 = 109
    BLOCK_110 = 110
    BLOCK_111 = 111
    BLOCK_112 = 112
    BLOCK_113 = 113
    BLOCK_114 = 114
    BLOCK_115 = 115
    BLOCK_116 = 116
    BLOCK_117 = 117
    BLOCK_118 = 118
    BLOCK_119 = 119
    BLOCK_120 = 120
    BLOCK_121 = 121
    BLOCK_122 = 122
    BLOCK_123 = 123
    BLOCK_124 = 124
    BLOCK_125 = 125
    BLOCK_126 = 126
    BLOCK_127 = 127
    BLOCK_128 = 128
    BLOCK_129 = 129
    BLOCK_130 = 130
    BLOCK_131 = 131
    BLOCK_132 = 132
    BLOCK_133 = 133
    BLOCK_134 = 134
    BLOCK_135 = 135
    BLOCK_136 = 136
    BLOCK_137 = 137
    BLOCK_138 = 138
    BLOCK_139 = 139
    BLOCK_140 = 140
    BLOCK_141 = 141
    BLOCK_142 = 142
    BLOCK_143 = 143
    BLOCK_144 = 144
    BLOCK_145 = 145
    BLOCK_146 = 146
    BLOCK_147 = 147
    BLOCK_148 = 148
    BLOCK_149 = 149

    # ADVANCED BLOCKS
    BLOCK_150 = 150
    BLOCK_151 = 151
    BLOCK_152 = 152
    BLOCK_153 = 153
    BLOCK_154 = 154
    BLOCK_155 = 155
    BLOCK_156 = 156
    BLOCK_157 = 157
    BLOCK_158 = 158
    BLOCK_159 = 159
    BLOCK_160 = 160
    BLOCK_161 = 161
    BLOCK_162 = 162
    BLOCK_163 = 163
    BLOCK_164 = 164
    BLOCK_165 = 165
    BLOCK_166 = 166
    BLOCK_167 = 167
    BLOCK_168 = 168
    BLOCK_169 = 169
    BLOCK_170 = 170
    BLOCK_171 = 171
    BLOCK_172 = 172
    BLOCK_173 = 173
    BLOCK_174 = 174
    BLOCK_175 = 175
    BLOCK_176 = 176
    BLOCK_177 = 177
    BLOCK_178 = 178
    BLOCK_179 = 179

    # PLACEHOLDER BLOCKS
    BLOCK_180 = 180
    BLOCK_181 = 181
    BLOCK_182 = 182
    BLOCK_183 = 183
    BLOCK_184 = 184
    BLOCK_185 = 185
    BLOCK_186 = 186
    BLOCK_187 = 187
    BLOCK_188 = 188
    BLOCK_189 = 189
    BLOCK_190 = 190
    BLOCK_191 = 191
    BLOCK_192 = 192
    BLOCK_193 = 193
    BLOCK_194 = 194
    BLOCK_195 = 195
    BLOCK_196 = 196
    BLOCK_197 = 197
    BLOCK_198 = 198
    BLOCK_199 = 199
    BLOCK_200 = 200
    BLOCK_201 = 201
    BLOCK_202 = 202
    BLOCK_203 = 203
    BLOCK_204 = 204
    BLOCK_205 = 205
    BLOCK_206 = 206
    BLOCK_207 = 207
    BLOCK_208 = 208
    BLOCK_209 = 209
    BLOCK_210 = 210
    BLOCK_211 = 211
    BLOCK_212 = 212
    BLOCK_213 = 213
    BLOCK_214 = 214
    BLOCK_215 = 215
    BLOCK_216 = 216
    BLOCK_217 = 217
    BLOCK_218 = 218
    BLOCK_219 = 219
    BLOCK_220 = 220
    BLOCK_221 = 221
    BLOCK_222 = 222
    BLOCK_223 = 223
    BLOCK_224 = 224
    BLOCK_225 = 225
    BLOCK_226 = 226
    BLOCK_227 = 227
    BLOCK_228 = 228
    BLOCK_229 = 229
    BLOCK_230 = 230
    BLOCK_231 = 231
    BLOCK_232 = 232
    BLOCK_233 = 233
    BLOCK_234 = 234
    BLOCK_235 = 235
    BLOCK_236 = 236
    BLOCK_237 = 237
    BLOCK_238 = 238
    BLOCK_239 = 239
    BLOCK_240 = 240
    BLOCK_241 = 241
    BLOCK_242 = 242
    BLOCK_243 = 243
    BLOCK_244 = 244
    BLOCK_245 = 245
    BLOCK_246 = 246
    BLOCK_247 = 247
    BLOCK_248 = 248
    BLOCK_249 = 249
    BLOCK_250 = 250
    BLOCK_251 = 251
    BLOCK_252 = 252
    BLOCK_253 = 253
    BLOCK_254 = 254
    BLOCK_255 = 255

    # Utility values
    COUNT = 257
    INVALID = 65535

# Block type constants for easier usage
class BlockTypes:
    """Convenient constants for block types"""
    # TERRAIN
    BLOCK_AIR = VoxelType.AIR
    BLOCK_STONE = VoxelType.STONE
    BLOCK_DIRT = VoxelType.DIRT
    BLOCK_GRASS = VoxelType.GRASS
    BLOCK_SAND = VoxelType.SAND
    BLOCK_GRAVEL = VoxelType.GRAVEL
    BLOCK_CLAY = VoxelType.CLAY
    BLOCK_BEDROCK = VoxelType.BEDROCK
    BLOCK_TOPSOIL = VoxelType.TOPSOIL
    BLOCK_SUBSOIL = VoxelType.SUBSOIL
    BLOCK_GRANITE = VoxelType.GRANITE
    BLOCK_LIMESTONE = VoxelType.LIMESTONE
    BLOCK_MARBLE = VoxelType.MARBLE
    BLOCK_SANDSTONE = VoxelType.SANDSTONE
    BLOCK_SLATE = VoxelType.SLATE
    BLOCK_BASALT = VoxelType.BASALT
    BLOCK_QUARTZITE = VoxelType.QUARTZITE
    BLOCK_OBSIDIAN = VoxelType.OBSIDIAN
    BLOCK_PUMICE = VoxelType.PUMICE
    BLOCK_SHALE = VoxelType.SHALE
    BLOCK_COAL_ORE = VoxelType.COAL_ORE
    BLOCK_IRON_ORE = VoxelType.IRON_ORE
    BLOCK_COPPER_ORE = VoxelType.COPPER_ORE
    BLOCK_TIN_ORE = VoxelType.TIN_ORE
    BLOCK_SILVER_ORE = VoxelType.SILVER_ORE
    BLOCK_GOLD_ORE = VoxelType.GOLD_ORE
    BLOCK_RUBY = VoxelType.RUBY
    BLOCK_SAPPHIRE = VoxelType.SAPPHIRE
    BLOCK_EMERALD = VoxelType.EMERALD
    BLOCK_DIAMOND = VoxelType.DIAMOND
    BLOCK_OAK_WOOD = VoxelType.OAK_WOOD
    BLOCK_PINE_WOOD = VoxelType.PINE_WOOD
    BLOCK_BIRCH_WOOD = VoxelType.BIRCH_WOOD
    BLOCK_MAHOGANY_WOOD = VoxelType.MAHOGANY_WOOD
    BLOCK_OAK_LEAVES = VoxelType.OAK_LEAVES
    BLOCK_PINE_LEAVES = VoxelType.PINE_LEAVES
    BLOCK_BIRCH_LEAVES = VoxelType.BIRCH_LEAVES
    BLOCK_PALM_LEAVES = VoxelType.PALM_LEAVES
    BLOCK_BROWN_MUSHROOM = VoxelType.BROWN_MUSHROOM
    BLOCK_RED_MUSHROOM = VoxelType.RED_MUSHROOM
    BLOCK_SNOW = VoxelType.SNOW
    BLOCK_ICE = VoxelType.ICE
    BLOCK_PACKED_ICE = VoxelType.PACKED_ICE
    BLOCK_CACTUS = VoxelType.CACTUS
    BLOCK_JUNGLE_VINE = VoxelType.JUNGLE_VINE
    BLOCK_PINK_CORAL = VoxelType.PINK_CORAL
    BLOCK_BLUE_CORAL = VoxelType.BLUE_CORAL
    BLOCK_SEAWEED = VoxelType.SEAWEED
    BLOCK_TUNDRA_MOSS = VoxelType.TUNDRA_MOSS
    BLOCK_DESERT_ROCK = VoxelType.DESERT_ROCK
    BLOCK_TEST_AUTO_ID = VoxelType.TEST_AUTO_ID

    # FLUIDS
    BLOCK_WATER = VoxelType.WATER
    BLOCK_LAVA = VoxelType.LAVA
    BLOCK_OIL = VoxelType.OIL
    BLOCK_ACID = VoxelType.ACID
    BLOCK_HONEY = VoxelType.HONEY
    BLOCK_STEAM = VoxelType.STEAM
    BLOCK_TOXIC_GAS = VoxelType.TOXIC_GAS
    BLOCK_NATURAL_GAS = VoxelType.NATURAL_GAS
    BLOCK_MAGICAL_MIST = VoxelType.MAGICAL_MIST
    BLOCK_SMOKE = VoxelType.SMOKE

    # PROCESSED
    BLOCK_STONE_BRICK = VoxelType.STONE_BRICK
    BLOCK_GRANITE_BRICK = VoxelType.GRANITE_BRICK
    BLOCK_MARBLE_TILE = VoxelType.MARBLE_TILE
    BLOCK_SANDSTONE_BRICK = VoxelType.SANDSTONE_BRICK
    BLOCK_SLATE_TILE = VoxelType.SLATE_TILE
    BLOCK_COBBLESTONE = VoxelType.COBBLESTONE
    BLOCK_SMOOTH_STONE = VoxelType.SMOOTH_STONE
    BLOCK_POLISHED_STONE = VoxelType.POLISHED_STONE
    BLOCK_CHISELED_STONE = VoxelType.CHISELED_STONE
    BLOCK_FLAGSTONE = VoxelType.FLAGSTONE
    BLOCK_OAK_PLANKS = VoxelType.OAK_PLANKS
    BLOCK_PINE_PLANKS = VoxelType.PINE_PLANKS
    BLOCK_BIRCH_PLANKS = VoxelType.BIRCH_PLANKS
    BLOCK_MAHOGANY_PLANKS = VoxelType.MAHOGANY_PLANKS
    BLOCK_OAK_BEAM = VoxelType.OAK_BEAM
    BLOCK_PINE_BEAM = VoxelType.PINE_BEAM
    BLOCK_HARDWOOD_BEAM = VoxelType.HARDWOOD_BEAM
    BLOCK_BAMBOO_PLANKS = VoxelType.BAMBOO_PLANKS
    BLOCK_CORK = VoxelType.CORK
    BLOCK_CHARCOAL_BLOCK = VoxelType.CHARCOAL_BLOCK
    BLOCK_IRON_BLOCK = VoxelType.IRON_BLOCK
    BLOCK_COPPER_BLOCK = VoxelType.COPPER_BLOCK
    BLOCK_BRONZE_BLOCK = VoxelType.BRONZE_BLOCK
    BLOCK_STEEL_BLOCK = VoxelType.STEEL_BLOCK
    BLOCK_SILVER_BLOCK = VoxelType.SILVER_BLOCK
    BLOCK_GOLD_BLOCK = VoxelType.GOLD_BLOCK
    BLOCK_BRASS_BLOCK = VoxelType.BRASS_BLOCK
    BLOCK_PEWTER_BLOCK = VoxelType.PEWTER_BLOCK
    BLOCK_MITHRIL_BLOCK = VoxelType.MITHRIL_BLOCK
    BLOCK_ADAMANTINE_BLOCK = VoxelType.ADAMANTINE_BLOCK
    BLOCK_CLAY_BRICK = VoxelType.CLAY_BRICK
    BLOCK_TERRACOTTA = VoxelType.TERRACOTTA
    BLOCK_WHITE_GLAZED_CERAMIC = VoxelType.WHITE_GLAZED_CERAMIC
    BLOCK_RED_GLAZED_CERAMIC = VoxelType.RED_GLAZED_CERAMIC
    BLOCK_BLUE_GLAZED_CERAMIC = VoxelType.BLUE_GLAZED_CERAMIC
    BLOCK_GREEN_GLAZED_CERAMIC = VoxelType.GREEN_GLAZED_CERAMIC
    BLOCK_PORCELAIN = VoxelType.PORCELAIN
    BLOCK_STONEWARE = VoxelType.STONEWARE
    BLOCK_EARTHENWARE = VoxelType.EARTHENWARE
    BLOCK_CERAMIC_TILE = VoxelType.CERAMIC_TILE

    # FUNCTIONAL
    BLOCK_BLOCK_100 = VoxelType.BLOCK_100
    BLOCK_BLOCK_101 = VoxelType.BLOCK_101
    BLOCK_BLOCK_102 = VoxelType.BLOCK_102
    BLOCK_BLOCK_103 = VoxelType.BLOCK_103
    BLOCK_BLOCK_104 = VoxelType.BLOCK_104
    BLOCK_BLOCK_105 = VoxelType.BLOCK_105
    BLOCK_BLOCK_106 = VoxelType.BLOCK_106
    BLOCK_BLOCK_107 = VoxelType.BLOCK_107
    BLOCK_BLOCK_108 = VoxelType.BLOCK_108
    BLOCK_BLOCK_109 = VoxelType.BLOCK_109
    BLOCK_BLOCK_110 = VoxelType.BLOCK_110
    BLOCK_BLOCK_111 = VoxelType.BLOCK_111
    BLOCK_BLOCK_112 = VoxelType.BLOCK_112
    BLOCK_BLOCK_113 = VoxelType.BLOCK_113
    BLOCK_BLOCK_114 = VoxelType.BLOCK_114
    BLOCK_BLOCK_115 = VoxelType.BLOCK_115
    BLOCK_BLOCK_116 = VoxelType.BLOCK_116
    BLOCK_BLOCK_117 = VoxelType.BLOCK_117
    BLOCK_BLOCK_118 = VoxelType.BLOCK_118
    BLOCK_BLOCK_119 = VoxelType.BLOCK_119
    BLOCK_BLOCK_120 = VoxelType.BLOCK_120
    BLOCK_BLOCK_121 = VoxelType.BLOCK_121
    BLOCK_BLOCK_122 = VoxelType.BLOCK_122
    BLOCK_BLOCK_123 = VoxelType.BLOCK_123
    BLOCK_BLOCK_124 = VoxelType.BLOCK_124
    BLOCK_BLOCK_125 = VoxelType.BLOCK_125
    BLOCK_BLOCK_126 = VoxelType.BLOCK_126
    BLOCK_BLOCK_127 = VoxelType.BLOCK_127
    BLOCK_BLOCK_128 = VoxelType.BLOCK_128
    BLOCK_BLOCK_129 = VoxelType.BLOCK_129
    BLOCK_BLOCK_130 = VoxelType.BLOCK_130
    BLOCK_BLOCK_131 = VoxelType.BLOCK_131
    BLOCK_BLOCK_132 = VoxelType.BLOCK_132
    BLOCK_BLOCK_133 = VoxelType.BLOCK_133
    BLOCK_BLOCK_134 = VoxelType.BLOCK_134
    BLOCK_BLOCK_135 = VoxelType.BLOCK_135
    BLOCK_BLOCK_136 = VoxelType.BLOCK_136
    BLOCK_BLOCK_137 = VoxelType.BLOCK_137
    BLOCK_BLOCK_138 = VoxelType.BLOCK_138
    BLOCK_BLOCK_139 = VoxelType.BLOCK_139
    BLOCK_BLOCK_140 = VoxelType.BLOCK_140
    BLOCK_BLOCK_141 = VoxelType.BLOCK_141
    BLOCK_BLOCK_142 = VoxelType.BLOCK_142
    BLOCK_BLOCK_143 = VoxelType.BLOCK_143
    BLOCK_BLOCK_144 = VoxelType.BLOCK_144
    BLOCK_BLOCK_145 = VoxelType.BLOCK_145
    BLOCK_BLOCK_146 = VoxelType.BLOCK_146
    BLOCK_BLOCK_147 = VoxelType.BLOCK_147
    BLOCK_BLOCK_148 = VoxelType.BLOCK_148
    BLOCK_BLOCK_149 = VoxelType.BLOCK_149

    # ADVANCED
    BLOCK_BLOCK_150 = VoxelType.BLOCK_150
    BLOCK_BLOCK_151 = VoxelType.BLOCK_151
    BLOCK_BLOCK_152 = VoxelType.BLOCK_152
    BLOCK_BLOCK_153 = VoxelType.BLOCK_153
    BLOCK_BLOCK_154 = VoxelType.BLOCK_154
    BLOCK_BLOCK_155 = VoxelType.BLOCK_155
    BLOCK_BLOCK_156 = VoxelType.BLOCK_156
    BLOCK_BLOCK_157 = VoxelType.BLOCK_157
    BLOCK_BLOCK_158 = VoxelType.BLOCK_158
    BLOCK_BLOCK_159 = VoxelType.BLOCK_159
    BLOCK_BLOCK_160 = VoxelType.BLOCK_160
    BLOCK_BLOCK_161 = VoxelType.BLOCK_161
    BLOCK_BLOCK_162 = VoxelType.BLOCK_162
    BLOCK_BLOCK_163 = VoxelType.BLOCK_163
    BLOCK_BLOCK_164 = VoxelType.BLOCK_164
    BLOCK_BLOCK_165 = VoxelType.BLOCK_165
    BLOCK_BLOCK_166 = VoxelType.BLOCK_166
    BLOCK_BLOCK_167 = VoxelType.BLOCK_167
    BLOCK_BLOCK_168 = VoxelType.BLOCK_168
    BLOCK_BLOCK_169 = VoxelType.BLOCK_169
    BLOCK_BLOCK_170 = VoxelType.BLOCK_170
    BLOCK_BLOCK_171 = VoxelType.BLOCK_171
    BLOCK_BLOCK_172 = VoxelType.BLOCK_172
    BLOCK_BLOCK_173 = VoxelType.BLOCK_173
    BLOCK_BLOCK_174 = VoxelType.BLOCK_174
    BLOCK_BLOCK_175 = VoxelType.BLOCK_175
    BLOCK_BLOCK_176 = VoxelType.BLOCK_176
    BLOCK_BLOCK_177 = VoxelType.BLOCK_177
    BLOCK_BLOCK_178 = VoxelType.BLOCK_178
    BLOCK_BLOCK_179 = VoxelType.BLOCK_179

    # PLACEHOLDER
    BLOCK_BLOCK_180 = VoxelType.BLOCK_180
    BLOCK_BLOCK_181 = VoxelType.BLOCK_181
    BLOCK_BLOCK_182 = VoxelType.BLOCK_182
    BLOCK_BLOCK_183 = VoxelType.BLOCK_183
    BLOCK_BLOCK_184 = VoxelType.BLOCK_184
    BLOCK_BLOCK_185 = VoxelType.BLOCK_185
    BLOCK_BLOCK_186 = VoxelType.BLOCK_186
    BLOCK_BLOCK_187 = VoxelType.BLOCK_187
    BLOCK_BLOCK_188 = VoxelType.BLOCK_188
    BLOCK_BLOCK_189 = VoxelType.BLOCK_189
    BLOCK_BLOCK_190 = VoxelType.BLOCK_190
    BLOCK_BLOCK_191 = VoxelType.BLOCK_191
    BLOCK_BLOCK_192 = VoxelType.BLOCK_192
    BLOCK_BLOCK_193 = VoxelType.BLOCK_193
    BLOCK_BLOCK_194 = VoxelType.BLOCK_194
    BLOCK_BLOCK_195 = VoxelType.BLOCK_195
    BLOCK_BLOCK_196 = VoxelType.BLOCK_196
    BLOCK_BLOCK_197 = VoxelType.BLOCK_197
    BLOCK_BLOCK_198 = VoxelType.BLOCK_198
    BLOCK_BLOCK_199 = VoxelType.BLOCK_199
    BLOCK_BLOCK_200 = VoxelType.BLOCK_200
    BLOCK_BLOCK_201 = VoxelType.BLOCK_201
    BLOCK_BLOCK_202 = VoxelType.BLOCK_202
    BLOCK_BLOCK_203 = VoxelType.BLOCK_203
    BLOCK_BLOCK_204 = VoxelType.BLOCK_204
    BLOCK_BLOCK_205 = VoxelType.BLOCK_205
    BLOCK_BLOCK_206 = VoxelType.BLOCK_206
    BLOCK_BLOCK_207 = VoxelType.BLOCK_207
    BLOCK_BLOCK_208 = VoxelType.BLOCK_208
    BLOCK_BLOCK_209 = VoxelType.BLOCK_209
    BLOCK_BLOCK_210 = VoxelType.BLOCK_210
    BLOCK_BLOCK_211 = VoxelType.BLOCK_211
    BLOCK_BLOCK_212 = VoxelType.BLOCK_212
    BLOCK_BLOCK_213 = VoxelType.BLOCK_213
    BLOCK_BLOCK_214 = VoxelType.BLOCK_214
    BLOCK_BLOCK_215 = VoxelType.BLOCK_215
    BLOCK_BLOCK_216 = VoxelType.BLOCK_216
    BLOCK_BLOCK_217 = VoxelType.BLOCK_217
    BLOCK_BLOCK_218 = VoxelType.BLOCK_218
    BLOCK_BLOCK_219 = VoxelType.BLOCK_219
    BLOCK_BLOCK_220 = VoxelType.BLOCK_220
    BLOCK_BLOCK_221 = VoxelType.BLOCK_221
    BLOCK_BLOCK_222 = VoxelType.BLOCK_222
    BLOCK_BLOCK_223 = VoxelType.BLOCK_223
    BLOCK_BLOCK_224 = VoxelType.BLOCK_224
    BLOCK_BLOCK_225 = VoxelType.BLOCK_225
    BLOCK_BLOCK_226 = VoxelType.BLOCK_226
    BLOCK_BLOCK_227 = VoxelType.BLOCK_227
    BLOCK_BLOCK_228 = VoxelType.BLOCK_228
    BLOCK_BLOCK_229 = VoxelType.BLOCK_229
    BLOCK_BLOCK_230 = VoxelType.BLOCK_230
    BLOCK_BLOCK_231 = VoxelType.BLOCK_231
    BLOCK_BLOCK_232 = VoxelType.BLOCK_232
    BLOCK_BLOCK_233 = VoxelType.BLOCK_233
    BLOCK_BLOCK_234 = VoxelType.BLOCK_234
    BLOCK_BLOCK_235 = VoxelType.BLOCK_235
    BLOCK_BLOCK_236 = VoxelType.BLOCK_236
    BLOCK_BLOCK_237 = VoxelType.BLOCK_237
    BLOCK_BLOCK_238 = VoxelType.BLOCK_238
    BLOCK_BLOCK_239 = VoxelType.BLOCK_239
    BLOCK_BLOCK_240 = VoxelType.BLOCK_240
    BLOCK_BLOCK_241 = VoxelType.BLOCK_241
    BLOCK_BLOCK_242 = VoxelType.BLOCK_242
    BLOCK_BLOCK_243 = VoxelType.BLOCK_243
    BLOCK_BLOCK_244 = VoxelType.BLOCK_244
    BLOCK_BLOCK_245 = VoxelType.BLOCK_245
    BLOCK_BLOCK_246 = VoxelType.BLOCK_246
    BLOCK_BLOCK_247 = VoxelType.BLOCK_247
    BLOCK_BLOCK_248 = VoxelType.BLOCK_248
    BLOCK_BLOCK_249 = VoxelType.BLOCK_249
    BLOCK_BLOCK_250 = VoxelType.BLOCK_250
    BLOCK_BLOCK_251 = VoxelType.BLOCK_251
    BLOCK_BLOCK_252 = VoxelType.BLOCK_252
    BLOCK_BLOCK_253 = VoxelType.BLOCK_253
    BLOCK_BLOCK_254 = VoxelType.BLOCK_254
    BLOCK_BLOCK_255 = VoxelType.BLOCK_255


# Lookup tables
BLOCK_NAME_TO_ID: Dict[str, int] = {
    # TERRAIN
    'AIR': 0,
    'STONE': 1,
    'DIRT': 2,
    'GRASS': 3,
    'SAND': 4,
    'GRAVEL': 5,
    'CLAY': 6,
    'BEDROCK': 7,
    'TOPSOIL': 8,
    'SUBSOIL': 9,
    'GRANITE': 10,
    'LIMESTONE': 11,
    'MARBLE': 12,
    'SANDSTONE': 13,
    'SLATE': 14,
    'BASALT': 15,
    'QUARTZITE': 16,
    'OBSIDIAN': 17,
    'PUMICE': 18,
    'SHALE': 19,
    'COAL_ORE': 20,
    'IRON_ORE': 21,
    'COPPER_ORE': 22,
    'TIN_ORE': 23,
    'SILVER_ORE': 24,
    'GOLD_ORE': 25,
    'RUBY': 26,
    'SAPPHIRE': 27,
    'EMERALD': 28,
    'DIAMOND': 29,
    'OAK_WOOD': 30,
    'PINE_WOOD': 31,
    'BIRCH_WOOD': 32,
    'MAHOGANY_WOOD': 33,
    'OAK_LEAVES': 34,
    'PINE_LEAVES': 35,
    'BIRCH_LEAVES': 36,
    'PALM_LEAVES': 37,
    'BROWN_MUSHROOM': 38,
    'RED_MUSHROOM': 39,
    'SNOW': 40,
    'ICE': 41,
    'PACKED_ICE': 42,
    'CACTUS': 43,
    'JUNGLE_VINE': 44,
    'PINK_CORAL': 45,
    'BLUE_CORAL': 46,
    'SEAWEED': 47,
    'TUNDRA_MOSS': 48,
    'DESERT_ROCK': 49,
    'TEST_AUTO_ID': 256,

    # FLUIDS
    'WATER': 50,
    'LAVA': 51,
    'OIL': 52,
    'ACID': 53,
    'HONEY': 54,
    'STEAM': 55,
    'TOXIC_GAS': 56,
    'NATURAL_GAS': 57,
    'MAGICAL_MIST': 58,
    'SMOKE': 59,

    # PROCESSED
    'STONE_BRICK': 60,
    'GRANITE_BRICK': 61,
    'MARBLE_TILE': 62,
    'SANDSTONE_BRICK': 63,
    'SLATE_TILE': 64,
    'COBBLESTONE': 65,
    'SMOOTH_STONE': 66,
    'POLISHED_STONE': 67,
    'CHISELED_STONE': 68,
    'FLAGSTONE': 69,
    'OAK_PLANKS': 70,
    'PINE_PLANKS': 71,
    'BIRCH_PLANKS': 72,
    'MAHOGANY_PLANKS': 73,
    'OAK_BEAM': 74,
    'PINE_BEAM': 75,
    'HARDWOOD_BEAM': 76,
    'BAMBOO_PLANKS': 77,
    'CORK': 78,
    'CHARCOAL_BLOCK': 79,
    'IRON_BLOCK': 80,
    'COPPER_BLOCK': 81,
    'BRONZE_BLOCK': 82,
    'STEEL_BLOCK': 83,
    'SILVER_BLOCK': 84,
    'GOLD_BLOCK': 85,
    'BRASS_BLOCK': 86,
    'PEWTER_BLOCK': 87,
    'MITHRIL_BLOCK': 88,
    'ADAMANTINE_BLOCK': 89,
    'CLAY_BRICK': 90,
    'TERRACOTTA': 91,
    'WHITE_GLAZED_CERAMIC': 92,
    'RED_GLAZED_CERAMIC': 93,
    'BLUE_GLAZED_CERAMIC': 94,
    'GREEN_GLAZED_CERAMIC': 95,
    'PORCELAIN': 96,
    'STONEWARE': 97,
    'EARTHENWARE': 98,
    'CERAMIC_TILE': 99,

    # FUNCTIONAL
    'BLOCK_100': 100,
    'BLOCK_101': 101,
    'BLOCK_102': 102,
    'BLOCK_103': 103,
    'BLOCK_104': 104,
    'BLOCK_105': 105,
    'BLOCK_106': 106,
    'BLOCK_107': 107,
    'BLOCK_108': 108,
    'BLOCK_109': 109,
    'BLOCK_110': 110,
    'BLOCK_111': 111,
    'BLOCK_112': 112,
    'BLOCK_113': 113,
    'BLOCK_114': 114,
    'BLOCK_115': 115,
    'BLOCK_116': 116,
    'BLOCK_117': 117,
    'BLOCK_118': 118,
    'BLOCK_119': 119,
    'BLOCK_120': 120,
    'BLOCK_121': 121,
    'BLOCK_122': 122,
    'BLOCK_123': 123,
    'BLOCK_124': 124,
    'BLOCK_125': 125,
    'BLOCK_126': 126,
    'BLOCK_127': 127,
    'BLOCK_128': 128,
    'BLOCK_129': 129,
    'BLOCK_130': 130,
    'BLOCK_131': 131,
    'BLOCK_132': 132,
    'BLOCK_133': 133,
    'BLOCK_134': 134,
    'BLOCK_135': 135,
    'BLOCK_136': 136,
    'BLOCK_137': 137,
    'BLOCK_138': 138,
    'BLOCK_139': 139,
    'BLOCK_140': 140,
    'BLOCK_141': 141,
    'BLOCK_142': 142,
    'BLOCK_143': 143,
    'BLOCK_144': 144,
    'BLOCK_145': 145,
    'BLOCK_146': 146,
    'BLOCK_147': 147,
    'BLOCK_148': 148,
    'BLOCK_149': 149,

    # ADVANCED
    'BLOCK_150': 150,
    'BLOCK_151': 151,
    'BLOCK_152': 152,
    'BLOCK_153': 153,
    'BLOCK_154': 154,
    'BLOCK_155': 155,
    'BLOCK_156': 156,
    'BLOCK_157': 157,
    'BLOCK_158': 158,
    'BLOCK_159': 159,
    'BLOCK_160': 160,
    'BLOCK_161': 161,
    'BLOCK_162': 162,
    'BLOCK_163': 163,
    'BLOCK_164': 164,
    'BLOCK_165': 165,
    'BLOCK_166': 166,
    'BLOCK_167': 167,
    'BLOCK_168': 168,
    'BLOCK_169': 169,
    'BLOCK_170': 170,
    'BLOCK_171': 171,
    'BLOCK_172': 172,
    'BLOCK_173': 173,
    'BLOCK_174': 174,
    'BLOCK_175': 175,
    'BLOCK_176': 176,
    'BLOCK_177': 177,
    'BLOCK_178': 178,
    'BLOCK_179': 179,

    # PLACEHOLDER
    'BLOCK_180': 180,
    'BLOCK_181': 181,
    'BLOCK_182': 182,
    'BLOCK_183': 183,
    'BLOCK_184': 184,
    'BLOCK_185': 185,
    'BLOCK_186': 186,
    'BLOCK_187': 187,
    'BLOCK_188': 188,
    'BLOCK_189': 189,
    'BLOCK_190': 190,
    'BLOCK_191': 191,
    'BLOCK_192': 192,
    'BLOCK_193': 193,
    'BLOCK_194': 194,
    'BLOCK_195': 195,
    'BLOCK_196': 196,
    'BLOCK_197': 197,
    'BLOCK_198': 198,
    'BLOCK_199': 199,
    'BLOCK_200': 200,
    'BLOCK_201': 201,
    'BLOCK_202': 202,
    'BLOCK_203': 203,
    'BLOCK_204': 204,
    'BLOCK_205': 205,
    'BLOCK_206': 206,
    'BLOCK_207': 207,
    'BLOCK_208': 208,
    'BLOCK_209': 209,
    'BLOCK_210': 210,
    'BLOCK_211': 211,
    'BLOCK_212': 212,
    'BLOCK_213': 213,
    'BLOCK_214': 214,
    'BLOCK_215': 215,
    'BLOCK_216': 216,
    'BLOCK_217': 217,
    'BLOCK_218': 218,
    'BLOCK_219': 219,
    'BLOCK_220': 220,
    'BLOCK_221': 221,
    'BLOCK_222': 222,
    'BLOCK_223': 223,
    'BLOCK_224': 224,
    'BLOCK_225': 225,
    'BLOCK_226': 226,
    'BLOCK_227': 227,
    'BLOCK_228': 228,
    'BLOCK_229': 229,
    'BLOCK_230': 230,
    'BLOCK_231': 231,
    'BLOCK_232': 232,
    'BLOCK_233': 233,
    'BLOCK_234': 234,
    'BLOCK_235': 235,
    'BLOCK_236': 236,
    'BLOCK_237': 237,
    'BLOCK_238': 238,
    'BLOCK_239': 239,
    'BLOCK_240': 240,
    'BLOCK_241': 241,
    'BLOCK_242': 242,
    'BLOCK_243': 243,
    'BLOCK_244': 244,
    'BLOCK_245': 245,
    'BLOCK_246': 246,
    'BLOCK_247': 247,
    'BLOCK_248': 248,
    'BLOCK_249': 249,
    'BLOCK_250': 250,
    'BLOCK_251': 251,
    'BLOCK_252': 252,
    'BLOCK_253': 253,
    'BLOCK_254': 254,
    'BLOCK_255': 255,

}

BLOCK_ID_TO_NAME: Dict[int, str] = {
    # TERRAIN
    0: 'AIR',
    1: 'STONE',
    2: 'DIRT',
    3: 'GRASS',
    4: 'SAND',
    5: 'GRAVEL',
    6: 'CLAY',
    7: 'BEDROCK',
    8: 'TOPSOIL',
    9: 'SUBSOIL',
    10: 'GRANITE',
    11: 'LIMESTONE',
    12: 'MARBLE',
    13: 'SANDSTONE',
    14: 'SLATE',
    15: 'BASALT',
    16: 'QUARTZITE',
    17: 'OBSIDIAN',
    18: 'PUMICE',
    19: 'SHALE',
    20: 'COAL_ORE',
    21: 'IRON_ORE',
    22: 'COPPER_ORE',
    23: 'TIN_ORE',
    24: 'SILVER_ORE',
    25: 'GOLD_ORE',
    26: 'RUBY',
    27: 'SAPPHIRE',
    28: 'EMERALD',
    29: 'DIAMOND',
    30: 'OAK_WOOD',
    31: 'PINE_WOOD',
    32: 'BIRCH_WOOD',
    33: 'MAHOGANY_WOOD',
    34: 'OAK_LEAVES',
    35: 'PINE_LEAVES',
    36: 'BIRCH_LEAVES',
    37: 'PALM_LEAVES',
    38: 'BROWN_MUSHROOM',
    39: 'RED_MUSHROOM',
    40: 'SNOW',
    41: 'ICE',
    42: 'PACKED_ICE',
    43: 'CACTUS',
    44: 'JUNGLE_VINE',
    45: 'PINK_CORAL',
    46: 'BLUE_CORAL',
    47: 'SEAWEED',
    48: 'TUNDRA_MOSS',
    49: 'DESERT_ROCK',
    256: 'TEST_AUTO_ID',

    # FLUIDS
    50: 'WATER',
    51: 'LAVA',
    52: 'OIL',
    53: 'ACID',
    54: 'HONEY',
    55: 'STEAM',
    56: 'TOXIC_GAS',
    57: 'NATURAL_GAS',
    58: 'MAGICAL_MIST',
    59: 'SMOKE',

    # PROCESSED
    60: 'STONE_BRICK',
    61: 'GRANITE_BRICK',
    62: 'MARBLE_TILE',
    63: 'SANDSTONE_BRICK',
    64: 'SLATE_TILE',
    65: 'COBBLESTONE',
    66: 'SMOOTH_STONE',
    67: 'POLISHED_STONE',
    68: 'CHISELED_STONE',
    69: 'FLAGSTONE',
    70: 'OAK_PLANKS',
    71: 'PINE_PLANKS',
    72: 'BIRCH_PLANKS',
    73: 'MAHOGANY_PLANKS',
    74: 'OAK_BEAM',
    75: 'PINE_BEAM',
    76: 'HARDWOOD_BEAM',
    77: 'BAMBOO_PLANKS',
    78: 'CORK',
    79: 'CHARCOAL_BLOCK',
    80: 'IRON_BLOCK',
    81: 'COPPER_BLOCK',
    82: 'BRONZE_BLOCK',
    83: 'STEEL_BLOCK',
    84: 'SILVER_BLOCK',
    85: 'GOLD_BLOCK',
    86: 'BRASS_BLOCK',
    87: 'PEWTER_BLOCK',
    88: 'MITHRIL_BLOCK',
    89: 'ADAMANTINE_BLOCK',
    90: 'CLAY_BRICK',
    91: 'TERRACOTTA',
    92: 'WHITE_GLAZED_CERAMIC',
    93: 'RED_GLAZED_CERAMIC',
    94: 'BLUE_GLAZED_CERAMIC',
    95: 'GREEN_GLAZED_CERAMIC',
    96: 'PORCELAIN',
    97: 'STONEWARE',
    98: 'EARTHENWARE',
    99: 'CERAMIC_TILE',

    # FUNCTIONAL
    100: 'BLOCK_100',
    101: 'BLOCK_101',
    102: 'BLOCK_102',
    103: 'BLOCK_103',
    104: 'BLOCK_104',
    105: 'BLOCK_105',
    106: 'BLOCK_106',
    107: 'BLOCK_107',
    108: 'BLOCK_108',
    109: 'BLOCK_109',
    110: 'BLOCK_110',
    111: 'BLOCK_111',
    112: 'BLOCK_112',
    113: 'BLOCK_113',
    114: 'BLOCK_114',
    115: 'BLOCK_115',
    116: 'BLOCK_116',
    117: 'BLOCK_117',
    118: 'BLOCK_118',
    119: 'BLOCK_119',
    120: 'BLOCK_120',
    121: 'BLOCK_121',
    122: 'BLOCK_122',
    123: 'BLOCK_123',
    124: 'BLOCK_124',
    125: 'BLOCK_125',
    126: 'BLOCK_126',
    127: 'BLOCK_127',
    128: 'BLOCK_128',
    129: 'BLOCK_129',
    130: 'BLOCK_130',
    131: 'BLOCK_131',
    132: 'BLOCK_132',
    133: 'BLOCK_133',
    134: 'BLOCK_134',
    135: 'BLOCK_135',
    136: 'BLOCK_136',
    137: 'BLOCK_137',
    138: 'BLOCK_138',
    139: 'BLOCK_139',
    140: 'BLOCK_140',
    141: 'BLOCK_141',
    142: 'BLOCK_142',
    143: 'BLOCK_143',
    144: 'BLOCK_144',
    145: 'BLOCK_145',
    146: 'BLOCK_146',
    147: 'BLOCK_147',
    148: 'BLOCK_148',
    149: 'BLOCK_149',

    # ADVANCED
    150: 'BLOCK_150',
    151: 'BLOCK_151',
    152: 'BLOCK_152',
    153: 'BLOCK_153',
    154: 'BLOCK_154',
    155: 'BLOCK_155',
    156: 'BLOCK_156',
    157: 'BLOCK_157',
    158: 'BLOCK_158',
    159: 'BLOCK_159',
    160: 'BLOCK_160',
    161: 'BLOCK_161',
    162: 'BLOCK_162',
    163: 'BLOCK_163',
    164: 'BLOCK_164',
    165: 'BLOCK_165',
    166: 'BLOCK_166',
    167: 'BLOCK_167',
    168: 'BLOCK_168',
    169: 'BLOCK_169',
    170: 'BLOCK_170',
    171: 'BLOCK_171',
    172: 'BLOCK_172',
    173: 'BLOCK_173',
    174: 'BLOCK_174',
    175: 'BLOCK_175',
    176: 'BLOCK_176',
    177: 'BLOCK_177',
    178: 'BLOCK_178',
    179: 'BLOCK_179',

    # PLACEHOLDER
    180: 'BLOCK_180',
    181: 'BLOCK_181',
    182: 'BLOCK_182',
    183: 'BLOCK_183',
    184: 'BLOCK_184',
    185: 'BLOCK_185',
    186: 'BLOCK_186',
    187: 'BLOCK_187',
    188: 'BLOCK_188',
    189: 'BLOCK_189',
    190: 'BLOCK_190',
    191: 'BLOCK_191',
    192: 'BLOCK_192',
    193: 'BLOCK_193',
    194: 'BLOCK_194',
    195: 'BLOCK_195',
    196: 'BLOCK_196',
    197: 'BLOCK_197',
    198: 'BLOCK_198',
    199: 'BLOCK_199',
    200: 'BLOCK_200',
    201: 'BLOCK_201',
    202: 'BLOCK_202',
    203: 'BLOCK_203',
    204: 'BLOCK_204',
    205: 'BLOCK_205',
    206: 'BLOCK_206',
    207: 'BLOCK_207',
    208: 'BLOCK_208',
    209: 'BLOCK_209',
    210: 'BLOCK_210',
    211: 'BLOCK_211',
    212: 'BLOCK_212',
    213: 'BLOCK_213',
    214: 'BLOCK_214',
    215: 'BLOCK_215',
    216: 'BLOCK_216',
    217: 'BLOCK_217',
    218: 'BLOCK_218',
    219: 'BLOCK_219',
    220: 'BLOCK_220',
    221: 'BLOCK_221',
    222: 'BLOCK_222',
    223: 'BLOCK_223',
    224: 'BLOCK_224',
    225: 'BLOCK_225',
    226: 'BLOCK_226',
    227: 'BLOCK_227',
    228: 'BLOCK_228',
    229: 'BLOCK_229',
    230: 'BLOCK_230',
    231: 'BLOCK_231',
    232: 'BLOCK_232',
    233: 'BLOCK_233',
    234: 'BLOCK_234',
    235: 'BLOCK_235',
    236: 'BLOCK_236',
    237: 'BLOCK_237',
    238: 'BLOCK_238',
    239: 'BLOCK_239',
    240: 'BLOCK_240',
    241: 'BLOCK_241',
    242: 'BLOCK_242',
    243: 'BLOCK_243',
    244: 'BLOCK_244',
    245: 'BLOCK_245',
    246: 'BLOCK_246',
    247: 'BLOCK_247',
    248: 'BLOCK_248',
    249: 'BLOCK_249',
    250: 'BLOCK_250',
    251: 'BLOCK_251',
    252: 'BLOCK_252',
    253: 'BLOCK_253',
    254: 'BLOCK_254',
    255: 'BLOCK_255',

}

BLOCK_CATEGORIES: Dict[str, Set[str]] = {
    'terrain': {
        'AIR',
        'STONE',
        'DIRT',
        'GRASS',
        'SAND',
        'GRAVEL',
        'CLAY',
        'BEDROCK',
        'TOPSOIL',
        'SUBSOIL',
        'GRANITE',
        'LIMESTONE',
        'MARBLE',
        'SANDSTONE',
        'SLATE',
        'BASALT',
        'QUARTZITE',
        'OBSIDIAN',
        'PUMICE',
        'SHALE',
        'COAL_ORE',
        'IRON_ORE',
        'COPPER_ORE',
        'TIN_ORE',
        'SILVER_ORE',
        'GOLD_ORE',
        'RUBY',
        'SAPPHIRE',
        'EMERALD',
        'DIAMOND',
        'OAK_WOOD',
        'PINE_WOOD',
        'BIRCH_WOOD',
        'MAHOGANY_WOOD',
        'OAK_LEAVES',
        'PINE_LEAVES',
        'BIRCH_LEAVES',
        'PALM_LEAVES',
        'BROWN_MUSHROOM',
        'RED_MUSHROOM',
        'SNOW',
        'ICE',
        'PACKED_ICE',
        'CACTUS',
        'JUNGLE_VINE',
        'PINK_CORAL',
        'BLUE_CORAL',
        'SEAWEED',
        'TUNDRA_MOSS',
        'DESERT_ROCK',
        'TEST_AUTO_ID',
    },
    'fluids': {
        'WATER',
        'LAVA',
        'OIL',
        'ACID',
        'HONEY',
        'STEAM',
        'TOXIC_GAS',
        'NATURAL_GAS',
        'MAGICAL_MIST',
        'SMOKE',
    },
    'processed': {
        'STONE_BRICK',
        'GRANITE_BRICK',
        'MARBLE_TILE',
        'SANDSTONE_BRICK',
        'SLATE_TILE',
        'COBBLESTONE',
        'SMOOTH_STONE',
        'POLISHED_STONE',
        'CHISELED_STONE',
        'FLAGSTONE',
        'OAK_PLANKS',
        'PINE_PLANKS',
        'BIRCH_PLANKS',
        'MAHOGANY_PLANKS',
        'OAK_BEAM',
        'PINE_BEAM',
        'HARDWOOD_BEAM',
        'BAMBOO_PLANKS',
        'CORK',
        'CHARCOAL_BLOCK',
        'IRON_BLOCK',
        'COPPER_BLOCK',
        'BRONZE_BLOCK',
        'STEEL_BLOCK',
        'SILVER_BLOCK',
        'GOLD_BLOCK',
        'BRASS_BLOCK',
        'PEWTER_BLOCK',
        'MITHRIL_BLOCK',
        'ADAMANTINE_BLOCK',
        'CLAY_BRICK',
        'TERRACOTTA',
        'WHITE_GLAZED_CERAMIC',
        'RED_GLAZED_CERAMIC',
        'BLUE_GLAZED_CERAMIC',
        'GREEN_GLAZED_CERAMIC',
        'PORCELAIN',
        'STONEWARE',
        'EARTHENWARE',
        'CERAMIC_TILE',
    },
    'functional': {
        'BLOCK_100',
        'BLOCK_101',
        'BLOCK_102',
        'BLOCK_103',
        'BLOCK_104',
        'BLOCK_105',
        'BLOCK_106',
        'BLOCK_107',
        'BLOCK_108',
        'BLOCK_109',
        'BLOCK_110',
        'BLOCK_111',
        'BLOCK_112',
        'BLOCK_113',
        'BLOCK_114',
        'BLOCK_115',
        'BLOCK_116',
        'BLOCK_117',
        'BLOCK_118',
        'BLOCK_119',
        'BLOCK_120',
        'BLOCK_121',
        'BLOCK_122',
        'BLOCK_123',
        'BLOCK_124',
        'BLOCK_125',
        'BLOCK_126',
        'BLOCK_127',
        'BLOCK_128',
        'BLOCK_129',
        'BLOCK_130',
        'BLOCK_131',
        'BLOCK_132',
        'BLOCK_133',
        'BLOCK_134',
        'BLOCK_135',
        'BLOCK_136',
        'BLOCK_137',
        'BLOCK_138',
        'BLOCK_139',
        'BLOCK_140',
        'BLOCK_141',
        'BLOCK_142',
        'BLOCK_143',
        'BLOCK_144',
        'BLOCK_145',
        'BLOCK_146',
        'BLOCK_147',
        'BLOCK_148',
        'BLOCK_149',
    },
    'advanced': {
        'BLOCK_150',
        'BLOCK_151',
        'BLOCK_152',
        'BLOCK_153',
        'BLOCK_154',
        'BLOCK_155',
        'BLOCK_156',
        'BLOCK_157',
        'BLOCK_158',
        'BLOCK_159',
        'BLOCK_160',
        'BLOCK_161',
        'BLOCK_162',
        'BLOCK_163',
        'BLOCK_164',
        'BLOCK_165',
        'BLOCK_166',
        'BLOCK_167',
        'BLOCK_168',
        'BLOCK_169',
        'BLOCK_170',
        'BLOCK_171',
        'BLOCK_172',
        'BLOCK_173',
        'BLOCK_174',
        'BLOCK_175',
        'BLOCK_176',
        'BLOCK_177',
        'BLOCK_178',
        'BLOCK_179',
    },
    'placeholder': {
        'BLOCK_180',
        'BLOCK_181',
        'BLOCK_182',
        'BLOCK_183',
        'BLOCK_184',
        'BLOCK_185',
        'BLOCK_186',
        'BLOCK_187',
        'BLOCK_188',
        'BLOCK_189',
        'BLOCK_190',
        'BLOCK_191',
        'BLOCK_192',
        'BLOCK_193',
        'BLOCK_194',
        'BLOCK_195',
        'BLOCK_196',
        'BLOCK_197',
        'BLOCK_198',
        'BLOCK_199',
        'BLOCK_200',
        'BLOCK_201',
        'BLOCK_202',
        'BLOCK_203',
        'BLOCK_204',
        'BLOCK_205',
        'BLOCK_206',
        'BLOCK_207',
        'BLOCK_208',
        'BLOCK_209',
        'BLOCK_210',
        'BLOCK_211',
        'BLOCK_212',
        'BLOCK_213',
        'BLOCK_214',
        'BLOCK_215',
        'BLOCK_216',
        'BLOCK_217',
        'BLOCK_218',
        'BLOCK_219',
        'BLOCK_220',
        'BLOCK_221',
        'BLOCK_222',
        'BLOCK_223',
        'BLOCK_224',
        'BLOCK_225',
        'BLOCK_226',
        'BLOCK_227',
        'BLOCK_228',
        'BLOCK_229',
        'BLOCK_230',
        'BLOCK_231',
        'BLOCK_232',
        'BLOCK_233',
        'BLOCK_234',
        'BLOCK_235',
        'BLOCK_236',
        'BLOCK_237',
        'BLOCK_238',
        'BLOCK_239',
        'BLOCK_240',
        'BLOCK_241',
        'BLOCK_242',
        'BLOCK_243',
        'BLOCK_244',
        'BLOCK_245',
        'BLOCK_246',
        'BLOCK_247',
        'BLOCK_248',
        'BLOCK_249',
        'BLOCK_250',
        'BLOCK_251',
        'BLOCK_252',
        'BLOCK_253',
        'BLOCK_254',
        'BLOCK_255',
    },
}

BLOCK_TO_CATEGORY: Dict[str, str] = {
    # TERRAIN
    'AIR': 'terrain',
    'STONE': 'terrain',
    'DIRT': 'terrain',
    'GRASS': 'terrain',
    'SAND': 'terrain',
    'GRAVEL': 'terrain',
    'CLAY': 'terrain',
    'BEDROCK': 'terrain',
    'TOPSOIL': 'terrain',
    'SUBSOIL': 'terrain',
    'GRANITE': 'terrain',
    'LIMESTONE': 'terrain',
    'MARBLE': 'terrain',
    'SANDSTONE': 'terrain',
    'SLATE': 'terrain',
    'BASALT': 'terrain',
    'QUARTZITE': 'terrain',
    'OBSIDIAN': 'terrain',
    'PUMICE': 'terrain',
    'SHALE': 'terrain',
    'COAL_ORE': 'terrain',
    'IRON_ORE': 'terrain',
    'COPPER_ORE': 'terrain',
    'TIN_ORE': 'terrain',
    'SILVER_ORE': 'terrain',
    'GOLD_ORE': 'terrain',
    'RUBY': 'terrain',
    'SAPPHIRE': 'terrain',
    'EMERALD': 'terrain',
    'DIAMOND': 'terrain',
    'OAK_WOOD': 'terrain',
    'PINE_WOOD': 'terrain',
    'BIRCH_WOOD': 'terrain',
    'MAHOGANY_WOOD': 'terrain',
    'OAK_LEAVES': 'terrain',
    'PINE_LEAVES': 'terrain',
    'BIRCH_LEAVES': 'terrain',
    'PALM_LEAVES': 'terrain',
    'BROWN_MUSHROOM': 'terrain',
    'RED_MUSHROOM': 'terrain',
    'SNOW': 'terrain',
    'ICE': 'terrain',
    'PACKED_ICE': 'terrain',
    'CACTUS': 'terrain',
    'JUNGLE_VINE': 'terrain',
    'PINK_CORAL': 'terrain',
    'BLUE_CORAL': 'terrain',
    'SEAWEED': 'terrain',
    'TUNDRA_MOSS': 'terrain',
    'DESERT_ROCK': 'terrain',
    'TEST_AUTO_ID': 'terrain',

    # FLUIDS
    'WATER': 'fluids',
    'LAVA': 'fluids',
    'OIL': 'fluids',
    'ACID': 'fluids',
    'HONEY': 'fluids',
    'STEAM': 'fluids',
    'TOXIC_GAS': 'fluids',
    'NATURAL_GAS': 'fluids',
    'MAGICAL_MIST': 'fluids',
    'SMOKE': 'fluids',

    # PROCESSED
    'STONE_BRICK': 'processed',
    'GRANITE_BRICK': 'processed',
    'MARBLE_TILE': 'processed',
    'SANDSTONE_BRICK': 'processed',
    'SLATE_TILE': 'processed',
    'COBBLESTONE': 'processed',
    'SMOOTH_STONE': 'processed',
    'POLISHED_STONE': 'processed',
    'CHISELED_STONE': 'processed',
    'FLAGSTONE': 'processed',
    'OAK_PLANKS': 'processed',
    'PINE_PLANKS': 'processed',
    'BIRCH_PLANKS': 'processed',
    'MAHOGANY_PLANKS': 'processed',
    'OAK_BEAM': 'processed',
    'PINE_BEAM': 'processed',
    'HARDWOOD_BEAM': 'processed',
    'BAMBOO_PLANKS': 'processed',
    'CORK': 'processed',
    'CHARCOAL_BLOCK': 'processed',
    'IRON_BLOCK': 'processed',
    'COPPER_BLOCK': 'processed',
    'BRONZE_BLOCK': 'processed',
    'STEEL_BLOCK': 'processed',
    'SILVER_BLOCK': 'processed',
    'GOLD_BLOCK': 'processed',
    'BRASS_BLOCK': 'processed',
    'PEWTER_BLOCK': 'processed',
    'MITHRIL_BLOCK': 'processed',
    'ADAMANTINE_BLOCK': 'processed',
    'CLAY_BRICK': 'processed',
    'TERRACOTTA': 'processed',
    'WHITE_GLAZED_CERAMIC': 'processed',
    'RED_GLAZED_CERAMIC': 'processed',
    'BLUE_GLAZED_CERAMIC': 'processed',
    'GREEN_GLAZED_CERAMIC': 'processed',
    'PORCELAIN': 'processed',
    'STONEWARE': 'processed',
    'EARTHENWARE': 'processed',
    'CERAMIC_TILE': 'processed',

    # FUNCTIONAL
    'BLOCK_100': 'functional',
    'BLOCK_101': 'functional',
    'BLOCK_102': 'functional',
    'BLOCK_103': 'functional',
    'BLOCK_104': 'functional',
    'BLOCK_105': 'functional',
    'BLOCK_106': 'functional',
    'BLOCK_107': 'functional',
    'BLOCK_108': 'functional',
    'BLOCK_109': 'functional',
    'BLOCK_110': 'functional',
    'BLOCK_111': 'functional',
    'BLOCK_112': 'functional',
    'BLOCK_113': 'functional',
    'BLOCK_114': 'functional',
    'BLOCK_115': 'functional',
    'BLOCK_116': 'functional',
    'BLOCK_117': 'functional',
    'BLOCK_118': 'functional',
    'BLOCK_119': 'functional',
    'BLOCK_120': 'functional',
    'BLOCK_121': 'functional',
    'BLOCK_122': 'functional',
    'BLOCK_123': 'functional',
    'BLOCK_124': 'functional',
    'BLOCK_125': 'functional',
    'BLOCK_126': 'functional',
    'BLOCK_127': 'functional',
    'BLOCK_128': 'functional',
    'BLOCK_129': 'functional',
    'BLOCK_130': 'functional',
    'BLOCK_131': 'functional',
    'BLOCK_132': 'functional',
    'BLOCK_133': 'functional',
    'BLOCK_134': 'functional',
    'BLOCK_135': 'functional',
    'BLOCK_136': 'functional',
    'BLOCK_137': 'functional',
    'BLOCK_138': 'functional',
    'BLOCK_139': 'functional',
    'BLOCK_140': 'functional',
    'BLOCK_141': 'functional',
    'BLOCK_142': 'functional',
    'BLOCK_143': 'functional',
    'BLOCK_144': 'functional',
    'BLOCK_145': 'functional',
    'BLOCK_146': 'functional',
    'BLOCK_147': 'functional',
    'BLOCK_148': 'functional',
    'BLOCK_149': 'functional',

    # ADVANCED
    'BLOCK_150': 'advanced',
    'BLOCK_151': 'advanced',
    'BLOCK_152': 'advanced',
    'BLOCK_153': 'advanced',
    'BLOCK_154': 'advanced',
    'BLOCK_155': 'advanced',
    'BLOCK_156': 'advanced',
    'BLOCK_157': 'advanced',
    'BLOCK_158': 'advanced',
    'BLOCK_159': 'advanced',
    'BLOCK_160': 'advanced',
    'BLOCK_161': 'advanced',
    'BLOCK_162': 'advanced',
    'BLOCK_163': 'advanced',
    'BLOCK_164': 'advanced',
    'BLOCK_165': 'advanced',
    'BLOCK_166': 'advanced',
    'BLOCK_167': 'advanced',
    'BLOCK_168': 'advanced',
    'BLOCK_169': 'advanced',
    'BLOCK_170': 'advanced',
    'BLOCK_171': 'advanced',
    'BLOCK_172': 'advanced',
    'BLOCK_173': 'advanced',
    'BLOCK_174': 'advanced',
    'BLOCK_175': 'advanced',
    'BLOCK_176': 'advanced',
    'BLOCK_177': 'advanced',
    'BLOCK_178': 'advanced',
    'BLOCK_179': 'advanced',

    # PLACEHOLDER
    'BLOCK_180': 'placeholder',
    'BLOCK_181': 'placeholder',
    'BLOCK_182': 'placeholder',
    'BLOCK_183': 'placeholder',
    'BLOCK_184': 'placeholder',
    'BLOCK_185': 'placeholder',
    'BLOCK_186': 'placeholder',
    'BLOCK_187': 'placeholder',
    'BLOCK_188': 'placeholder',
    'BLOCK_189': 'placeholder',
    'BLOCK_190': 'placeholder',
    'BLOCK_191': 'placeholder',
    'BLOCK_192': 'placeholder',
    'BLOCK_193': 'placeholder',
    'BLOCK_194': 'placeholder',
    'BLOCK_195': 'placeholder',
    'BLOCK_196': 'placeholder',
    'BLOCK_197': 'placeholder',
    'BLOCK_198': 'placeholder',
    'BLOCK_199': 'placeholder',
    'BLOCK_200': 'placeholder',
    'BLOCK_201': 'placeholder',
    'BLOCK_202': 'placeholder',
    'BLOCK_203': 'placeholder',
    'BLOCK_204': 'placeholder',
    'BLOCK_205': 'placeholder',
    'BLOCK_206': 'placeholder',
    'BLOCK_207': 'placeholder',
    'BLOCK_208': 'placeholder',
    'BLOCK_209': 'placeholder',
    'BLOCK_210': 'placeholder',
    'BLOCK_211': 'placeholder',
    'BLOCK_212': 'placeholder',
    'BLOCK_213': 'placeholder',
    'BLOCK_214': 'placeholder',
    'BLOCK_215': 'placeholder',
    'BLOCK_216': 'placeholder',
    'BLOCK_217': 'placeholder',
    'BLOCK_218': 'placeholder',
    'BLOCK_219': 'placeholder',
    'BLOCK_220': 'placeholder',
    'BLOCK_221': 'placeholder',
    'BLOCK_222': 'placeholder',
    'BLOCK_223': 'placeholder',
    'BLOCK_224': 'placeholder',
    'BLOCK_225': 'placeholder',
    'BLOCK_226': 'placeholder',
    'BLOCK_227': 'placeholder',
    'BLOCK_228': 'placeholder',
    'BLOCK_229': 'placeholder',
    'BLOCK_230': 'placeholder',
    'BLOCK_231': 'placeholder',
    'BLOCK_232': 'placeholder',
    'BLOCK_233': 'placeholder',
    'BLOCK_234': 'placeholder',
    'BLOCK_235': 'placeholder',
    'BLOCK_236': 'placeholder',
    'BLOCK_237': 'placeholder',
    'BLOCK_238': 'placeholder',
    'BLOCK_239': 'placeholder',
    'BLOCK_240': 'placeholder',
    'BLOCK_241': 'placeholder',
    'BLOCK_242': 'placeholder',
    'BLOCK_243': 'placeholder',
    'BLOCK_244': 'placeholder',
    'BLOCK_245': 'placeholder',
    'BLOCK_246': 'placeholder',
    'BLOCK_247': 'placeholder',
    'BLOCK_248': 'placeholder',
    'BLOCK_249': 'placeholder',
    'BLOCK_250': 'placeholder',
    'BLOCK_251': 'placeholder',
    'BLOCK_252': 'placeholder',
    'BLOCK_253': 'placeholder',
    'BLOCK_254': 'placeholder',
    'BLOCK_255': 'placeholder',

}

# Utility functions

def get_block_id(block_name: str) -> Optional[int]:
    """Get block ID by name"""
    return BLOCK_NAME_TO_ID.get(block_name)

def get_block_name(block_id: int) -> Optional[str]:
    """Get block name by ID"""
    return BLOCK_ID_TO_NAME.get(block_id)

def is_valid_block_id(block_id: int) -> bool:
    """Check if block ID is valid"""
    return block_id in BLOCK_ID_TO_NAME

def is_valid_block_name(block_name: str) -> bool:
    """Check if block name is valid"""
    return block_name in BLOCK_NAME_TO_ID

def get_block_category(block_name: str) -> Optional[str]:
    """Get category for a block"""
    return BLOCK_TO_CATEGORY.get(block_name)

def get_blocks_in_category(category: str) -> Set[str]:
    """Get all block names in a category"""
    return BLOCK_CATEGORIES.get(category, set())

def get_all_categories() -> List[str]:
    """Get list of all categories"""
    return list(BLOCK_CATEGORIES.keys())

def get_all_block_names() -> List[str]:
    """Get list of all block names"""
    return list(BLOCK_NAME_TO_ID.keys())

def get_all_block_ids() -> List[int]:
    """Get list of all block IDs"""
    return list(BLOCK_ID_TO_NAME.keys())

# Category checking functions
def is_terrain(block_name: str) -> bool:
    """Check if block is in terrain category"""
    return get_block_category(block_name) == 'terrain'

def is_fluids(block_name: str) -> bool:
    """Check if block is in fluids category"""
    return get_block_category(block_name) == 'fluids'

def is_processed(block_name: str) -> bool:
    """Check if block is in processed category"""
    return get_block_category(block_name) == 'processed'

def is_functional(block_name: str) -> bool:
    """Check if block is in functional category"""
    return get_block_category(block_name) == 'functional'

def is_advanced(block_name: str) -> bool:
    """Check if block is in advanced category"""
    return get_block_category(block_name) == 'advanced'

def is_placeholder(block_name: str) -> bool:
    """Check if block is in placeholder category"""
    return get_block_category(block_name) == 'placeholder'

# Generation metadata
GENERATION_INFO = {
    "timestamp": "2025-06-08T16:10:39.581504",
    "total_blocks": 257,
    "categories": ['terrain', 'fluids', 'processed', 'functional', 'advanced', 'placeholder'],
    "blocks_per_category": {
        "terrain": 51,
        "fluids": 10,
        "processed": 40,
        "functional": 50,
        "advanced": 30,
        "placeholder": 76,
    }
}

